/* PAYUU LIVE - SINGLE MEDIA ENGAGEMENT OVERLAY */
(function () {
'use strict';
if (window.__PAYUU_ENGAGEMENT_RUNTIME__) return;
window.__PAYUU_ENGAGEMENT_RUNTIME__ = true;
const TYPES={like:{icon:'❤️',title:'LIKE THE STREAM',message:'Smash that Like button!'},subscribe:{icon:'🔔',title:'SUBSCRIBE',message:'Subscribe to Payuu Live and join the community!'},share:{icon:'📣',title:'SHARE THE STREAM',message:'Share the stream and help the community grow!'}};
const queue=[];const seen=new Set();let busy=false;let activeTimer=null;let listenerStarted=false;let browserChannel=null;let currentVideo=null;let currentAudioVideo=null;let currentAudio=null;let currentCanvas=null;let drawFrame=0;
function removeStrayText(){try{const w=document.createTreeWalker(document.body||document,NodeFilter.SHOW_TEXT),r=[];let n;while(n=w.nextNode()){if(n.nodeValue&&n.nodeValue.includes('window.payuuEngagementShow'))r.push(n)}r.forEach(n=>n.parentNode&&n.parentNode.removeChild(n))}catch(_){} }
function isolateEngagementFromNormalOverlay(){try{if(!window.firebaseDB||typeof window.firebaseDB.listenOverlay!=='function'||window.firebaseDB.__payuuEngagementIsolated)return;window.firebaseDB.listenOverlay=function(callback){const db=window.firebase&&typeof firebase.database==='function'?firebase.database():null;if(!db)return;const ref=db.ref('overlayQueue');let initialized=false;const initialKeys=new Set();const pending=[];const handle=snap=>{const data=snap.val(),key=snap.key;if(!initialized){pending.push([data,key]);return}if(initialKeys.has(key))return;if(data&&data.eventType==='engagement')return;callback(data,key)};ref.on('child_added',handle);ref.once('value').then(snap=>{snap.forEach(child=>{initialKeys.add(child.key)});initialized=true;pending.forEach(([data,key])=>{if(!initialKeys.has(key)&&data&&data.eventType!=='engagement')callback(data,key)});}).catch(()=>{initialized=true;pending.forEach(([data,key])=>{if(data&&data.eventType!=='engagement')callback(data,key)})});};window.firebaseDB.__payuuEngagementIsolated=true}catch(_){} }
function createUI(){if(document.getElementById('payuu-engagement-media'))return;const s=document.createElement('style');s.id='payuu-engagement-media-style';s.textContent=`#payuu-engagement-media{position:fixed!important;inset:0!important;display:flex!important;align-items:center;justify-content:center;z-index:99999!important;pointer-events:none;opacity:0;visibility:hidden;transition:opacity .35s ease,visibility .35s ease}.payuu-engagement-media-inner{position:relative;display:flex;flex-direction:column;align-items:center;justify-content:center;max-width:90vw;max-height:90vh;text-align:center}.payuu-engagement-media-asset{display:block;max-width:90vw;max-height:72vh;width:auto;height:auto;object-fit:contain;filter:drop-shadow(0 0 25px rgba(255,215,0,.55));border-radius:18px}.payuu-engagement-source{position:absolute!important;width:2px!important;height:2px!important;opacity:0!important;left:-9999px!important;pointer-events:none!important}.payuu-engagement-media-title{margin-top:12px;padding:8px 18px;border-radius:999px;background:rgba(7,25,47,.88);border:1px solid #FFD700;color:#FFD700;font:900 1.5rem/1.1 Orbitron,Arial,sans-serif;text-shadow:0 0 12px rgba(255,215,0,.45)}.payuu-engagement-media-message{margin-top:6px;color:#fff;font:700 .9rem Poppins,Arial,sans-serif;text-shadow:0 2px 8px #000}#payuu-engagement-media.active{opacity:1!important;visibility:visible!important}@media(max-width:600px){.payuu-engagement-media-asset{max-width:94vw;max-height:65vh}.payuu-engagement-media-title{font-size:1.1rem}.payuu-engagement-media-message{font-size:.75rem}}`;document.head.appendChild(s);const b=document.createElement('div');b.id='payuu-engagement-media';b.innerHTML=`<div class="payuu-engagement-media-inner"><div id="payuu-engagement-media-slot"></div><div id="payuu-engagement-media-title" class="payuu-engagement-media-title"></div><div id="payuu-engagement-media-message" class="payuu-engagement-media-message"></div><audio id="payuu-engagement-media-audio" class="payuu-engagement-source" preload="auto"></audio></div>`;document.body.appendChild(b)}
function parseEvent(data){const msg=String(data?.msg||'');const match=msg.match(/^\[\[PAYUU_ENGAGEMENT:(like|subscribe|share)\]\]\s*/i);if(!match&&data?.eventType!=='engagement')return null;const type=String(data?.engagementType||match?.[1]||'like').toLowerCase();return{type,message:match?msg.slice(match[0].length).trim():String(data?.message||''),mediaUrl:data?.engagementMediaUrl||'/assets/engagement/engagement.mp4',mediaType:data?.engagementMediaType||'video/mp4',soundUrl:data?.engagementSoundUrl||'',duration:Math.max(1,Math.min(30,Number(data?.engagementDuration||6))),volume:Math.max(0,Math.min(1,Number(data?.engagementVolume??1)))}}
function clearMedia(){cancelAnimationFrame(drawFrame);drawFrame=0;const s=document.getElementById('payuu-engagement-media-slot'),a=document.getElementById('payuu-engagement-media-audio');[currentVideo,currentAudioVideo].forEach(v=>{if(v){try{v.pause();v.removeAttribute('src');v.load()}catch(_){} }});currentVideo=null;currentAudioVideo=null;currentCanvas=null;if(s)s.innerHTML='';if(a){a.pause();a.removeAttribute('src');a.load()}currentAudio=null}
function isGreen(r,g,b){return g>100&&g>r*1.35&&g>b*1.25&&g-r>35&&g-b>25}
function playMediaElement(el){try{const p=el.play();if(p&&typeof p.catch==='function')p.catch(err=>console.warn('Engagement media autoplay:',err));}catch(err){console.warn('Engagement media play:',err)}}
function startChromaVideo(url,slot,volume,soundUrl){const v=document.createElement('video');v.className='payuu-engagement-source';v.src=url;v.playsInline=true;v.controls=false;v.preload='auto';v.muted=true;v.volume=0;slot.appendChild(v);currentVideo=v;const canvas=document.createElement('canvas');canvas.className='payuu-engagement-media-asset';slot.appendChild(canvas);currentCanvas=canvas;const ctx=canvas.getContext('2d',{willReadFrequently:true});const resize=()=>{if(v.videoWidth&&v.videoHeight){if(canvas.width!==v.videoWidth||canvas.height!==v.videoHeight){canvas.width=v.videoWidth;canvas.height=v.videoHeight}}};const frame=()=>{if(currentVideo!==v)return;resize();if(v.readyState>=2&&canvas.width&&canvas.height){ctx.drawImage(v,0,0,canvas.width,canvas.height);const image=ctx.getImageData(0,0,canvas.width,canvas.height);const p=image.data;for(let i=0;i<p.length;i+=4){const r=p[i],g=p[i+1],b=p[i+2];if(isGreen(r,g,b)){p[i+3]=0}else if(g>r*1.22&&g>b*1.16&&g-r>24){const alpha=Math.max(0,Math.min(255,255-(g-Math.max(r,b))*3));p[i+3]=Math.min(p[i+3],alpha)}}ctx.putImageData(image,0,0)}drawFrame=requestAnimationFrame(frame)};v.addEventListener('loadedmetadata',()=>{resize();frame()});v.addEventListener('loadeddata',frame);v.addEventListener('canplay',()=>{resize();frame();playMediaElement(v)});v.addEventListener('play',frame);v.addEventListener('ended',()=>cancelAnimationFrame(drawFrame));playMediaElement(v);if(soundUrl){const a=document.getElementById('payuu-engagement-media-audio');if(a){a.src=soundUrl;a.volume=volume;a.currentTime=0;currentAudio=a;playMediaElement(a)}}else{const av=document.createElement('video');av.className='payuu-engagement-source';av.src=url;av.playsInline=true;av.controls=false;av.preload='auto';av.muted=false;av.volume=volume;slot.appendChild(av);currentAudioVideo=av;av.addEventListener('loadedmetadata',()=>playMediaElement(av));av.addEventListener('canplay',()=>playMediaElement(av));playMediaElement(av)}}
function render(item){const e=parseEvent(item.data);if(!e)return false;const identity=String(item.data?.id||item.key||'');if(identity&&seen.has(identity))return true;if(identity)seen.add(identity);if(busy){queue.push(item);return true}createUI();const b=document.getElementById('payuu-engagement-media'),s=document.getElementById('payuu-engagement-media-slot'),t=document.getElementById('payuu-engagement-media-title'),m=document.getElementById('payuu-engagement-media-message');if(!b||!s){queue.push(item);return true}busy=true;clearMedia();const c=TYPES[e.type]||TYPES.like;t.textContent=c.title;m.textContent=e.message||c.message;startChromaVideo(e.mediaUrl,s,e.volume,e.soundUrl);b.classList.remove('active');void b.offsetWidth;b.classList.add('active');try{if(typeof confetti==='function')confetti({particleCount:90,spread:90,origin:{y:.55}})}catch(_){}clearTimeout(activeTimer);activeTimer=setTimeout(()=>{b.classList.remove('active');setTimeout(()=>{clearMedia();busy=false;const n=queue.shift();if(n)render(n)},350)},e.duration*1000);return true}
function receive(data,source){if(data&&data.eventType==='engagement')render({data,key:source+'-'+(data.id||Date.now())})}
function listenBrowser(){try{if('BroadcastChannel' in window){browserChannel=new BroadcastChannel('payuu-engagement-v1');browserChannel.onmessage=e=>receive(e.data,'bc')}}catch(_){}try{window.addEventListener('storage',e=>{if(e.key==='payuu-engagement-event'&&e.newValue){try{receive(JSON.parse(e.newValue),'storage')}catch(_){} }});}catch(_){} }
function listenFresh(ref,source){return ref.once('value').then(snap=>{snap.forEach(child=>{if(child.key)seen.add(child.key);const v=child.val();if(v?.id)seen.add(String(v.id));});ref.on('child_added',snap=>receive(snap.val(),source));}).catch(()=>{ref.on('child_added',snap=>receive(snap.val(),source));});}
function listenQueue(){if(listenerStarted)return;if(!window.firebase||typeof firebase.database!=='function')return;listenerStarted=true;const dbRef=firebase.database();listenFresh(dbRef.ref('engagementBroadcast'),'firebase');listenFresh(dbRef.ref('overlayQueue'),'overlay');listenBrowser();}
window.payuuEngagementShow=function(data,key){return parseEvent(data)?render({data,key}):false};
isolateEngagementFromNormalOverlay();
document.addEventListener('DOMContentLoaded',()=>{removeStrayText();isolateEngagementFromNormalOverlay();createUI();listenQueue();listenBrowser()});
function waitForFirebase(){if(window.firebase&&typeof firebase.database==='function'){isolateEngagementFromNormalOverlay();listenQueue();listenBrowser();return}setTimeout(waitForFirebase,300)}
waitForFirebase();setTimeout(removeStrayText,100);
})();
