/* PAYUU LIVE - SINGLE CONFIGURABLE ENGAGEMENT OVERLAY */
(function () {
'use strict';
const CONFIGS={like:{icon:'❤️',title:'LIKE THE STREAM',message:'Smash that Like button!'},subscribe:{icon:'🔔',title:'SUBSCRIBE',message:'Subscribe to Payuu Live and join the community!'},share:{icon:'📣',title:'SHARE THE STREAM',message:'Share the stream and help the community grow!'}};
let busy=false,queue=[];
function createUI(){if(document.getElementById('payuu-engagement-alert'))return;const s=document.createElement('style');s.textContent=`#payuu-engagement-alert{position:fixed;inset:0;display:flex;align-items:center;justify-content:center;z-index:99999;pointer-events:none;opacity:0;transition:opacity .35s;background:transparent}#payuu-engagement-alert.active{opacity:1}#payuu-engagement-card{position:relative;width:min(850px,92vw);text-align:center;padding:25px;border-radius:24px;background:rgba(7,25,47,.9);border:2px solid #FFD700;box-shadow:0 0 45px rgba(255,215,0,.5);transform:scale(.75);transition:transform .45s cubic-bezier(.34,1.56,.64,1)}#payuu-engagement-alert.active #payuu-engagement-card{transform:scale(1)}#payuu-engagement-gif{display:none;max-width:100%;max-height:420px;margin:auto;border-radius:18px;object-fit:contain}#payuu-engagement-icon{font-size:4rem}#payuu-engagement-title{margin-top:10px;font:900 2.1rem Orbitron,Arial,sans-serif;color:#FFD700;text-shadow:0 0 15px rgba(255,215,0,.6)}#payuu-engagement-message{margin-top:8px;color:#fff;font:700 1rem Poppins,Arial,sans-serif}#payuu-engagement-brand{margin-top:12px;color:#00F0FF;font-weight:800;letter-spacing:2px;font-size:.7rem}@media(max-width:600px){#payuu-engagement-title{font-size:1.4rem}#payuu-engagement-icon{font-size:3rem}#payuu-engagement-gif{max-height:300px}}`;document.head.appendChild(s);const b=document.createElement('div');b.id='payuu-engagement-alert';b.innerHTML='<div id="payuu-engagement-card"><img id="payuu-engagement-gif" alt="Engagement animation"><div id="payuu-engagement-icon"></div><div id="payuu-engagement-title"></div><div id="payuu-engagement-message"></div><div id="payuu-engagement-brand">PAYUU LIVE</div></div>';document.body.appendChild(b);}
function render(data,key){const type=String(data?.engagementType||'').toLowerCase();const marker=String(data?.msg||'').match(/PAYUU_ENGAGEMENT:(like|subscribe|share)/i);const t=type|| (marker?marker[1].toLowerCase():'');if(!CONFIGS[t])return false;if(busy){queue.push({data,key});return true}const c=CONFIGS[t],box=document.getElementById('payuu-engagement-alert'),gif=document.getElementById('payuu-engagement-gif'),icon=document.getElementById('payuu-engagement-icon');busy=true;icon.textContent=c.icon;document.getElementById('payuu-engagement-title').textContent=c.title;document.getElementById('payuu-engagement-message').textContent=c.message;if(data.engagementGifUrl){gif.src=data.engagementGifUrl;gif.style.display='block';icon.style.display='none'}else{gif.style.display='none';icon.style.display='block'}box.classList.remove('active');void box.offsetWidth;box.classList.add('active');let audio;if(data.engagementSoundUrl){try{audio=new Audio(data.engagementSoundUrl);audio.volume=Math.max(0,Math.min(1,Number(data.engagementVolume??1)));audio.play().catch(()=>{});}catch(_){}}try{if(typeof confetti==='function')confetti({particleCount:100,spread:100,origin:{y:.5}})}catch(_){}const duration=Math.max(1,Math.min(30,Number(data.engagementDuration||6)))*1000;setTimeout(()=>{box.classList.remove('active');setTimeout(()=>{if(audio){audio.pause();audio.currentTime=0}if(key&&window.firebaseDB?.removeOverlayAlert)window.firebaseDB.removeOverlayAlert(key).catch(()=>{});busy=false;const next=queue.shift();if(next)render(next.data,next.key)},450)},duration);return true;}
window.payuuEngagementShow=render;document.addEventListener('DOMContentLoaded',()=>createUI());
})();
