/* PAYUU LIVE - SINGLE ENGAGEMENT OVERLAY CONTROL */
(function () {
'use strict';
const TYPES={like:{icon:'❤️',title:'LIKE THE STREAM',message:'Smash that Like button!'},subscribe:{icon:'🔔',title:'SUBSCRIBE',message:'Subscribe to Payuu Live and join the community!'},share:{icon:'📣',title:'SHARE THE STREAM',message:'Share the stream and help the community grow!'}};
const FIXED_MEDIA_URL='/assets/engagement/engagement.mp4';
const FIXED_MEDIA_TYPE='video/mp4';
let config={mediaUrl:FIXED_MEDIA_URL,mediaType:FIXED_MEDIA_TYPE,soundUrl:'',duration:6,volume:1};
const db=()=>window.firebase&&typeof firebase.database==='function'?firebase.database():null;
const st=()=>window.firebase&&typeof firebase.storage==='function'?firebase.storage():null;
function status(t,ok=false){const e=document.getElementById('engagement-status');if(e){e.textContent=t;e.style.color=ok?'#7CFFB2':'#FFD700';}}
function load(){const d=db();if(!d)return;d.ref('settings/engagementOverlay').once('value').then(s=>{if(s.val())config={...config,...s.val(),mediaUrl:FIXED_MEDIA_URL,mediaType:FIXED_MEDIA_TYPE};else config={...config,mediaUrl:FIXED_MEDIA_URL,mediaType:FIXED_MEDIA_TYPE};const du=document.getElementById('eng-duration'),vo=document.getElementById('eng-volume');if(du)du.value=config.duration;if(vo)vo.value=config.volume;const info=document.getElementById('eng-media-info');if(info)info.textContent='✓ Fixed engagement video: assets/engagement/engagement.mp4';}).catch(()=>{});}
async function upload(file,kind){if(!file)return;const s=st();if(!s||!firebase.auth().currentUser)throw Error('Please sign in first.');let ok=false,max=0;if(kind==='media'){ok=['image/png','image/jpeg','image/gif','video/mp4'].includes(file.type);max=50;}else{ok=file.type.startsWith('audio/');max=10;}if(!ok)throw Error(kind==='media'?'Supported media: PNG, JPG/JPEG, GIF or MP4 video.':'Please select an audio file.');if(file.size>max*1024*1024)throw Error(kind==='media'?`Media must be ${max} MB or smaller.`:'Sound must be 10 MB or smaller.');status('Uploading '+kind+'...');const ext=(file.name.split('.').pop()||'bin').toLowerCase();const path='engagement-assets/'+kind+'-'+Date.now()+'.'+ext;const r=s.ref(path);await r.put(file,{contentType:file.type,cacheControl:'public,max-age=3600'});config[kind==='media'?'mediaUrl':'soundUrl']=await r.getDownloadURL();if(kind==='media')status('✓ Upload saved. The engagement trigger uses the fixed GitHub video.',true);await save();if(kind==='sound')status('✓ SOUND uploaded and saved.',true);load();}
async function save(){const d=db();if(!d)throw Error('Firebase database is not connected.');config.mediaUrl=FIXED_MEDIA_URL;config.mediaType=FIXED_MEDIA_TYPE;config.duration=Math.max(1,Math.min(30,Number(document.getElementById('eng-duration')?.value)||6));config.volume=Math.max(0,Math.min(1,Number(document.getElementById('eng-volume')?.value)||1));await d.ref('settings/engagementOverlay').set(config);}
function broadcastBrowser(payload){try{if('BroadcastChannel' in window){const c=new BroadcastChannel('payuu-engagement-v1');c.postMessage(payload);c.close();}}catch(_){}try{localStorage.setItem('payuu-engagement-event',JSON.stringify({...payload,_nonce:Date.now()+'-'+Math.random()}));}catch(_){} }
async function trigger(type){const c=TYPES[type];if(!c)throw Error('Invalid engagement type.');const payload={eventType:'engagement',engagementType:type,name:c.title,amount:0,msg:`[[PAYUU_ENGAGEMENT:${type}]] ${c.message}`,engagementMediaUrl:FIXED_MEDIA_URL,engagementMediaType:FIXED_MEDIA_TYPE,engagementSoundUrl:config.soundUrl||'',engagementDuration:config.duration,engagementVolume:config.volume,approvedKey:'engagement',timestamp:firebase.database.ServerValue.TIMESTAMP};try{const d=db();if(!d)throw Error('Firebase database is not connected.');const r=d.ref('overlayQueue').push();payload.id=r.key;await r.set(payload);broadcastBrowser(payload);status('✓ '+c.title+' triggered.',true);}catch(e){status(e&&e.code==='PERMISSION_DENIED'?'PERMISSION_DENIED: Firebase is blocking this overlay write.':'ERROR: '+(e.message||e),false);throw e;}}
function create(){if(document.getElementById('payuu-engagement-single'))return;const p=document.getElementById('admin-panel');if(!p)return;const b=document.createElement('button');b.id='payuu-engagement-single';b.type='button';b.textContent='📣 ENGAGEMENT OVERLAY';p.insertBefore(b,p.firstChild);b.onclick=()=>document.getElementById('payuu-engagement-modal').classList.add('open');const m=document.createElement('div');m.id='payuu-engagement-modal';m.innerHTML=`<div class="eng-card"><button id="eng-close">✕</button><h2>📣 ENGAGEMENT OVERLAY</h2><p>One overlay • One media file • One sound • Three actions.</p><label>🎬 Upload Media<input id="eng-media" type="file" accept="image/png,image/jpeg,image/gif,video/mp4"><small>PNG, JPG/JPEG, GIF or MP4 video • Max 50 MB</small><div id="eng-media-info"></div></label><label>🔊 Upload Sound<input id="eng-sound" type="file" accept="audio/*"><small>MP3, WAV, OGG, M4A • Max 10 MB</small></label><div class="eng-row"><label>Duration<input id="eng-duration" type="number" min="1" max="30" value="6"></label><label>Volume<input id="eng-volume" type="number" min="0" max="1" step=".1" value="1"></label></div><button id="eng-save">💾 SAVE SETTINGS</button><h3>TRIGGER SAME OVERLAY</h3><div class="eng-actions"><button data-a="like">❤️ LIKE</button><button data-a="subscribe">🔔 SUBSCRIBE</button><button data-a="share">📣 SHARE</button></div><div id="engagement-status"></div></div>`;document.body.appendChild(m);document.getElementById('eng-close').onclick=()=>m.classList.remove('open');document.getElementById('eng-media').onchange=e=>upload(e.target.files[0],'media').catch(e=>status(e.message));document.getElementById('eng-sound').onchange=e=>upload(e.target.files[0],'sound').catch(e=>status(e.message));document.getElementById('eng-save').onclick=()=>save().then(()=>status('✓ Settings saved.',true)).catch(e=>status(e.message));m.querySelectorAll('[data-a]').forEach(x=>x.onclick=()=>trigger(x.dataset.a).catch(()=>{}));load();style();}
function style(){if(document.getElementById('eng-style'))return;const s=document.createElement('style');s.id='eng-style';s.textContent=`#payuu-engagement-single{width:100%;padding:15px;margin:0 0 18px;border:1px solid #FFD700;border-radius:14px;background:rgba(255,215,0,.1);color:#FFD700;font-weight:900;font-size:.95rem;cursor:pointer}#payuu-engagement-modal{display:none;position:fixed;inset:0;z-index:100000;background:rgba(0,0,0,.78);align-items:center;justify-content:center;padding:18px}#payuu-engagement-modal.open{display:flex}.eng-card{position:relative;width:min(560px,100%);max-height:90vh;overflow:auto;padding:22px;border:1px solid #FFD700;border-radius:20px;background:#07192F;color:#fff}.eng-card h2{color:#FFD700}.eng-card p,.eng-card small{color:#A0B3C6;font-size:.8rem}.eng-card>button:first-child{position:absolute;right:12px;top:10px;background:none;border:0;color:#fff;font-size:20px}.eng-card label{display:block;padding:13px;margin:10px 0;border:1px dashed #566b80;border-radius:10px}.eng-card input{display:block;width:100%;margin-top:7px}.eng-card small{display:block;margin-top:6px}.eng-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.eng-row input{padding:9px;background:#0b2b4a;color:#fff;border:1px solid #36506b;border-radius:8px}.eng-card #eng-save{width:100%;padding:12px;border:0;border-radius:10px;background:#FFD700;color:#07192F;font-weight:900}.eng-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.eng-actions button{padding:12px;border-radius:10px;background:#12304c;color:#fff;border:1px solid #49627a;font-weight:800}.eng-card h3{text-align:center;color:#00F0FF;font-size:.8rem}#engagement-status{text-align:center;min-height:20px;margin-top:10px;color:#FFD700;font-size:.75rem}#eng-media-info{margin-top:7px;color:#7CFFB2;font-size:.72rem}@media(max-width:600px){.eng-actions,.eng-row{grid-template-columns:1fr}}`;document.head.appendChild(s);}
function wait(){if(!window.firebaseDB||typeof window.firebaseDB.onAuthStateChanged!=='function')return setTimeout(wait,300);window.firebaseDB.onAuthStateChanged(u=>{if(u)window.firebaseDB.checkAdminStatus(u.email,r=>{if(r?.active===true){window.PayuuAdminState=r;create();}});});}
document.addEventListener('DOMContentLoaded',wait);
})();
